name: fake_api_consumer
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.4

dependencies:
  http: 1.2.1  
  dartz: 0.10.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
